### ISSUE TITLE
Fetch.go  (monthlyTodos - invalid argument reading zip file)

### ISSUE THREAD

**Issue by HackG** [gocodo/bloomnpi#2]
I edited the error message to give me more info where I'm getting this invalid argument error. It appears to be failing to read the zip. I can confirm it downloaded the zip ok however I just realized the Go version I have installed is go1.2.1 linux/amd64

Do you think simply updating to 1.3 would resolve this?

Original error msg said:

```
            Error: read data/NPPES_Data_Dissemination_June_2015.zip: invalid argument
```

Error msg source:

```
            reader, err := helpers.OpenReader("data/" + monthlyTodos[0] + ".zip")
            if err != nil {
                    fmt.Println("Error monthlyTodos-reader helpers-openreader:", err)
                    return
            }
```

Screenshot shows invalid argument with my edited error msg
![2015-07-10_1038](https://cloud.githubusercontent.com/assets/4760021/8620781/e9eec0fa-26ef-11e5-8443-a17e8231c192.png)

**Comment by untoldone** [comment]
Updating to 1.3 would likely fix this. I'm not entirely sure why the error is 'invalid argument', but go 1.2's zip support had a bug for zip file contents over 4GB which the NPI file is. See https://code.google.com/p/go/issues/detail?id=7069.

Give 1.3+ a try and see if it fixes your issue? Feel free to reopen this if this doesn't fix your issue.

**Comment by HackG** [comment]
It was indeed that - installed 1.4.1 and it ran just fine with no errors. Thanks!
